name: image_classifier
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  pytorch_lite: ^4.3.2 
  image_picker: ^1.1.2    
  camera: ^0.11.1     
  image: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/labels/label_classification_imageNet.txt
    - assets/models/model_classification.pt

  